set editor to vim. add cppcheck. set filetype plugin on

diff --git a/install b/install
--- a/install
+++ b/install
@@ -76,11 +76,11 @@ if ! type "git" > /dev/null; then
     echo "git is not installed, install git and rerun install script"
 else
     gitEditor="$(which vi)"
-#    if ! type "emacsclient" 2> /dev/null; then
-#        echo "could not find emacsclient, setting git editor to vim"
-#    else
-#        gitEditor="$(which emacsclient) -t"
-#    fi
+    if ! type "vim" 2> /dev/null; then
+        echo "could not find vim, setting git editor to vi"
+    else
+        gitEditor="vim"
+    fi
     echo "setting up git"
     git config --global core.editor "$gitEditor"
     git config --global core.excludesfile "$HOME/.gitignore_global"
